name: Tests
on: [push]
jobs:
  PrettierJS:
    runs-on: ubuntu-latest
    container: node:22-stretch
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run prettier-diff
  Lint:
    runs-on: ubuntu-latest
    container: node:22-stretch
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run lint-diff
  Jest:
    runs-on: ubuntu-latest
    container: node:22-stretch
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run test
